{
    'name': 'Coffee Shop Management',
    'version': '17.0.1.0.0',
    'depends': [
        'base',
        'sale_management',
        'product',
        'report_xlsx',
    ],
    'author': 'Odoo Development Foundation',
    'category': 'Services/Restaurant',
    'data': [
        'security/ir.model.access.csv',
        'views/menu_views.xml',
        'views/coffee_shop_views.xml',
        'views/carrer_views.xml',
        'views/consumption_views.xml',
        'views/meal_views.xml',
        'views/student_views.xml',
        'data/ir_sequence.xml',
        'data/product.xml',
        'views/sale_order_views.xml',
        'views/res_partner_views.xml',
        'wizards/wizard_consumption_report_views.xml',
        'wizards/wizard_consumption_excel_views.xml',
        'report/report_student_pdf.xml',
        'report/report_consumption_pdf.xml',
        'report/report_excel.xml',
    ],
    'installable': True,
    'application': True,
}