{
    "name": "Coffeshop 2.0",
    "version": "17.0.1.0.0",
    "category": "Services/Restaurant",
    "summary": "Gestión de cafetería escolar",
    "author": "Odoo Developers Foundation",
    "website": "",
    "depends": [
        "base",
        "sale_management",
        'product',
        'report_xlsx',
                ],
    "data": [
        "security/ir.model.access.csv", 
        "views/coffeshop_views.xml",
        "views/meal_views.xml",
        "views/student_views.xml",
        "views/carrer_views.xml",
        "views/consumption_views.xml",
        "views/coffeshop_menu.xml",
        "data/ir_sequence.xml",
        "data/product.xml",
        "views/sale_order_views.xml",
        "views/res_partner_views.xml",
        "wizards/wizard_consumption_report_views.xml",
        "report/report_consumption_pdf.xml",
        "wizards/wizard_consumption_excel_views.xml",
        "report/report_excel.xml",

    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
